#include <iostream>
#include <windows.h>
#include <time.h>
#include <string>
using namespace std;

int random(int _low, int _high)
{
    return rand() % ((_high + 1) - _low) + _low;
}

string name()
{
    //Created new string variables to hold each of the letter combinations that had to be used.
    string th = "Th";
    string ch = "Ch";
    string sh = "Sh";
    string qu = "Qu";
    string st = "St";

    //Created a seperate array for each letter combination that was required. Each array is the ending to a name that starts with the letter combination.
    string thName[14] = {"ackery", "ea", "eo", "eodore", "eresa", "iago", "addeus", "alia", "eodosia", "omas", "elma", "ompson", "anos", "or"};
    string chName[15] = {"ace", "adwick", "anel", "arlie", "astity", "az", "eryl", "loe", "ris", "ristian", "ristina", "ristopher", "ucky", "andler", "arlotte"};
    string shName[17] = {"amus", "aron", "awn", "epard", "akira", "ane", "annon", "aun", "elby", "erlock", "irley", "yanne", "yloh", "adow", "auna", "erman", "ayleen"};
    string quName[6] = {"entin", "incy", "inn", "ill", "illian", "isha"};
    string stName[18] = {"acey", "arley", "efan", "ephen", "even", "ory", "ella", "evie", "orm", "uart", "ark", "ephanie", "eve", "rider", "arling", "arla", "ellar", "ormy"};

    string name = "";

    //Created a variable to hold a random number for my switch statement.
    int index = random(1, 5);

    //Switch statement uses the random number generated to decide what letter combination and list of endings to use.
    switch (index)
    {
    //Names are generated by first pulling the letter combination variable, and then adding one of endings at random to the letter combination.
    case 1:
        name = th;
        name += thName[rand() % 14];
        break;

    case 2:
        name = ch;
        name += chName[rand() % 15];
        break;

    case 3:
        name = sh;
        name += shName[rand() % 17];
        break;

    case 4:
        name = qu;
        name += quName[rand() % 6];
        break;

    case 5:
        name = st;
        name += stName[rand() % 18];
        break;
    }

    return name;
}

int main()
{
    srand(time(NULL));

    for (int i = 0; i < 100; i++)
    {
        cout << name() << endl;
    }

    system("pause");
    return 0;
}